const QUESTION_TYPES = {
  DESCRIPTION: 'DESCRIPTION',
  ESSAY: 'ESSAY',
  MATCH: 'MATCHING',
  MC: 'MULTIPLE_CHOICE',
  NUMERIC: 'NUMERIC',
  SHORT: 'SHORT_ANSWER',
  TF: 'TRUE_FALSE'
};

module.exports = QUESTION_TYPES;
